Add --print-build-logs to flake transient
NixOS/nix-mode pull request #150
Opened 2022-02-26 01:14 UTC by chasecaleb

I find this option essential for `nix build`, so I added it to the flake transient.

2022-02-26 05:27 UTC, akirak requested changes
Thank you for sending this PR.  I think it is a good idea to add `--print-build-logs`. Maybe it should be the default? It would be better for us to allow customization of the default options, but this PR looks good to me. 

When I first implemented this library, I chose to use a two-letter sequence for options that consist of multiple words (like `-nu` for `--no-update-lock-file`).  Even with this rule, there will be conflicts when we add support for more options. For example, `--sandbox`, `--store`, and `--substituters` can conflict for `s`. Maybe we need better rules for abbreviating options, but we don't need to discuss short options available in the CLI, like `-L`.

2022-02-26 20:08 UTC, chasecaleb commented on nix-flake.el
> +   ("-p" "Print build logs" "--print-build-logs")]
Good advice, I overlooked that there was a short arg version in the CLI. I changed it to `-L`.

2022-02-26 20:12 UTC, chasecaleb commented
I agree with both your points. I changed it to `-L` and also made it enabled by default.

> It would be better for us to allow customization of the default options

Users can already set defaults using `transient-save`, which is bound to `C-x C-s` within transients. I didn't know about it for a long time until I went hunting though, and I suspect a lot of other transient users don't know about it as well, so maybe you could mention it in your readme or something along those lines to raise awareness.

---

Thanks for the quick feedback, by the way!

2022-02-27 05:17 UTC, akirak commented
@chasecaleb 

> Users can already set defaults using transient-save, which is bound to C-x C-s within transients.

Thank you for the information. I knew transient has many features, but I didn't dig into it. 

I don't have an admin permission on this repository, nor can @matthewbauer give me the permission to me, so please wait for a further response.

2022-02-28 15:20 UTC, merged